# .goreleaser.yml file
# https://github.com/robinovitch61/wander/
# Documentation at http://goreleaser.com
#
# Thanks to @neomantra for setup work on this https://github.com/robinovitch61/wander/issues/33

project_name: wander

before:
  hooks:
    - go mod tidy

builds:
  - binary: wander
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - freebsd
      - linux
      - windows

archives:
  - name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}Darwin
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

universal_binaries:
  - replace: true

release:
  github:
    owner: robinovitch61
    name: wander

brews:
  - name: wander
    homepage: https://github.com/robinovitch61/wander
    description: "An efficient terminal application/TUI for interacting with your HashiCorp Nomad cluster."
    folder: Formula
    commit_author:
      name: "Leo Robinovitch"
      email: "leorobinovitch@gmail.com"
    commit_msg_template: "Brew formula update for {{ .ProjectName }} version {{ .Tag }}"
    repository:
      owner: robinovitch61
      name: homebrew-tap
      branch: main
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"

aurs:
  - name: "wander-bin"
    homepage: "https://github.com/robinovitch61/wander"
    description: "An efficient terminal application/TUI for interacting with your HashiCorp Nomad cluster."
    maintainers:
        - "Leo Robinovitch <leorobinovitch@gmail.com>"
    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/wander-bin.git"
    depends:
      - "glibc"
    commit_author:
      name: "Leo Robinovitch"
      email: "leorobinovitch@gmail.com"
    skip_upload: auto

nix:
  - name: wander
    commit_author:
      name: "Leo Robinovitch"
      email: "leorobinovitch@gmail.com"
    homepage: "https://github.com/robinovitch61/wander"
    description: "An efficient terminal application/TUI for interacting with your HashiCorp Nomad cluster."
    license: "mit"  # must be lowercase
    skip_upload: auto
    repository:
      owner: robinovitch61
      name: nur-packages
      branch: main
      token: "{{ .Env.NUR_PACKAGES_GITHUB_TOKEN }}"

gomod:
  proxy: true
